format_version: 10
pipelines:
  jaguarjava:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-680cb9e:
        git: https://github.com/alanadiprastyo/jaguar-java-1.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - install
                command: mvn
                run_if: passed
